### ISSUE TITLE
Apriboti reikiamus registracijos laukus į alfanumerinius simbolius

### ISSUE THREAD

**Issue by emiliskiskis** [emiliskiskis/StudyBuddy#16]
Su dabartiniu funkcionalumu registracijos bei login laukuose leidžiami visi Unikodo simboliai. Norint užtikrinti tinkamą duomenų bazės veikimą, reikia apriboti `username` ir `email` laukus į alfanumerius simbolius ir `_` simbolį, o `password` ir `passwordConfirm` laukus alfanumerinius simbolius ir matomus ASCII skyrybos ženklus (pvz. `!@#$%^&*()-_=+/.<>:;"[]{}~`).

**Comment by MrCrit** [comment]
pridėjau šiuos apribojimus į email bei username laukus (kartu su -. leidžiamais). Password regex reikia atnaujinti, kad būtų galima naudoti ir skyrybos ženklus, @laujustas turėtų rast lengvai, kaip tai padaryt.

**Comment by laujustas** [comment]
Sutvarkiau password regex, dabar galima naudot ASCII charakterius 33-126.

**Comment by emiliskiskis** [comment]
Problema išspręsta su #15.
