### ISSUE TITLE
Kai Vartotojas jungiasi prie kito vartotojo antrą kartą, pirmasis vartotojas nebeišsiunčia žinučių

### ISSUE THREAD

**Issue by MrCrit** [emiliskiskis/StudyBuddy#2]
Skundžiasi BackgroundWorker. Gal kas netingi ir nori sutvarkyt šį bugą?

**Comment by emiliskiskis** [comment]
Reikėtų paprasčiausiai uždėti "connected" būseną, ar ne?

**Comment by MrCrit** [comment]
Neturėtų būt per daug sunku, gal Titas arba Justas nori susipažinti su programa bei sutvarkyti iškilusią problemą?

**Comment by emiliskiskis** [comment]
Susipažinti su programa ne nori, o jau reikia 😄

**Comment by emiliskiskis** [comment]
Problemos sprendimas nebereikalingas, keisim logikos pagrindus.
